server:
  port: 8000

spring:
  cloud:
    loadbalancer:
      configurations: health-check
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: multiplications
          uri: lb://multiplication/multiplications
          predicates:
            - Path=/api/multiplications/**
        - id: results
          uri: lb://multiplication/results
          predicates:
            - Path=/api/results/**
            - Method=GET,POST
        - id: leaders
          uri: lb://gamification/leaders
          predicates:
            - Path=/api/leaders/**
        - id: stats
          uri: lb://gamification/stats
          predicates:
            - Path=/api/stats/**
  application:
    name: gateway

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
